  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.6
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
